version: 2
jobs:
  build:
    docker:
      - image: abcum/circle-node:latest
    working_directory: /js/src/github.com/abcum/www.surrealdb.com
    steps:
      - checkout
      - run:
          name: Clean
          command: make clean
      - run:
          name: Setup
          command: make setup
      - run:
          name: Tests
          command: make tests
      - run:
          name: Build
          command: make build
      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              if [ ! -z "${CIRCLE_TAG}" ]; then
               make deploy
              fi
            fi
